algoritmo "Velocidade"

var
km,t,vm:real
inicio
// distancia e a velocidade
escreval("Entre com a distância percorrida")
Leia (km)
escreval("Entre com o tempo em horas diferente de ZERO")
Leia (t)
vm<-km/t
se vm>110 entao
   escreval("Você superou o limite de velocidade")
senao
   escreval("Sua velocidade média foi inferior ao limite de velocidade")
fimse
escreval("Limite:110")
escreval("Velocidade média:",Vm)

escreval("valor do combustivel 3,85")


fimalgoritmo